accent = "#7aaa28"
cursor = "#cccc7e"
foreground = "#cccc7e"
background = "#0e1c1e"
selection_foreground = "#cccc7e"
selection_background = "#7aaa28"

color0  = "#3a4555"
color1  = "#8a5e1e"
color2  = "#72a828"
color3  = "#b8521e"
color4  = "#6a8a28"
color5  = "#b85c38"
color6  = "#c2b830"
color7  = "#cccc7e"
color8  = "#4d5f72"
color9  = "#a5722e"
color10 = "#90d033"
color11 = "#e06428"
color12 = "#85ac34"
color13 = "#d87450"
color14 = "#d8cc40"
color15 = "#e0e09a"
